/**
 * Catálogo de prueba (espejo del seed demo) para pruebas unitarias del diseñador.
 * Sólo se importa desde *.test.ts.
 */
import type { DesignerCatalog } from "./types";
import type { DesignerInput } from "../schemas";

const mx = (pesos: number) => pesos * 100;

const STYLES = ["natural", "elegante", "romantico", "divertido", "minimal", "colorido"];
const ALL_ADDONS_BUT_KARAOKE = [
  "addon_pastel-personalizado",
  "addon_fotografo-2h",
  "addon_mimosa-bar",
  "addon_upgrade-floral",
  "addon_taller-floral",
  "addon_papeleria-personalizada",
  "addon_regalo-homenajeada",
  "addon_video-recap",
  "addon_memory-capsule-premium",
  "addon_arco-globos-organico",
  "addon_mesa-postres",
];

export function fixtureCatalog(): DesignerCatalog {
  return {
    pricing: {
      taxRateBps: 1600,
      pricesIncludeTax: true,
      depositBps: 5000,
      paymentFeeBps: 360,
      paymentFeeFixedCents: 300,
      minMarginBps: 3500,
      maxStandardGuests: 12,
    },
    styles: [
      {
        id: "style_natural",
        slug: "natural",
        name: "Natural",
        description: "Lino crudo, madera, follaje fresco y flores de campo.",
        palette: ["#F7F3EC", "#E8DCC8", "#A3B18A", "#5C6B4E"],
        sortOrder: 0,
      },
      {
        id: "style_elegante",
        slug: "elegante",
        name: "Elegante",
        description: "Cristalería fina, candelabros de latón y flores blancas.",
        palette: ["#FFFFFF", "#E8DCC8", "#C6A15B", "#2F2C2A"],
        sortOrder: 1,
      },
      {
        id: "style_romantico",
        slug: "romantico",
        name: "Romántico",
        description: "Rosas de jardín, tonos blush y velas encendidas.",
        palette: ["#F3E1DA", "#E9C9BE", "#F7F3EC", "#A48F7E"],
        sortOrder: 2,
      },
      {
        id: "style_divertido",
        slug: "divertido",
        name: "Divertido",
        description: "Globos orgánicos, colores alegres y detalles que invitan a la fiesta.",
        palette: ["#F4B6A6", "#F6D27A", "#A8D5C2", "#8FB3E0"],
        sortOrder: 3,
      },
      {
        id: "style_minimal",
        slug: "minimal",
        name: "Minimal",
        description: "Menos es más: blancos rotos y líneas limpias.",
        palette: ["#FFFFFF", "#F7F3EC", "#D9D4CC", "#2F2C2A"],
        sortOrder: 4,
      },
      {
        id: "style_colorido",
        slug: "colorido",
        name: "Colorido",
        description: "Papel picado, textiles artesanales y flores vibrantes.",
        palette: ["#D6336C", "#F4A261", "#2A9D8F", "#E9C46A"],
        sortOrder: 5,
      },
    ],
    areas: [
      { id: "area_polanco", slug: "polanco", name: "Polanco", logisticsFeeCents: mx(350) },
      { id: "area_granada", slug: "granada", name: "Granada", logisticsFeeCents: mx(350) },
      { id: "area_irrigacion", slug: "irrigacion", name: "Irrigación", logisticsFeeCents: mx(450) },
    ],
    budgets: [
      { id: "budget_1", label: "Hasta $15,000", minCents: 0, maxCents: mx(15_000) },
      { id: "budget_2", label: "$15,000 – $20,000", minCents: mx(15_000), maxCents: mx(20_000) },
      { id: "budget_3", label: "$20,000 – $30,000", minCents: mx(20_000), maxCents: mx(30_000) },
      { id: "budget_4", label: "$30,000 – $45,000", minCents: mx(30_000), maxCents: mx(45_000) },
      { id: "budget_5", label: "Más de $45,000", minCents: mx(45_000), maxCents: null },
    ],
    menus: [
      {
        id: "menu_brunch-clasico",
        slug: "brunch-clasico",
        name: "Brunch Clásico",
        description: "Chilaquiles, benedictinos, pan dulce artesanal y fruta de temporada.",
        pricingType: "INCLUDED",
        priceCents: 0,
        tags: ["clásico", "dulce y salado", "favorito"],
        dietaryTags: [],
        itemNames: [
          "Café de especialidad",
          "Chilaquiles verdes o rojos con pollo",
          "Huevos benedictinos con jamón serrano",
          "Mini hotcakes con frutos rojos",
        ],
        sortOrder: 0,
      },
      {
        id: "menu_brunch-garden",
        slug: "brunch-garden",
        name: "Brunch Garden",
        description: "Nuestra versión 100% vegetariana: fresca, colorida y con mucho sabor de huerto.",
        pricingType: "INCLUDED",
        priceCents: 0,
        tags: ["vegetariano", "ligero", "de temporada"],
        dietaryTags: ["VEGETARIAN"],
        itemNames: [
          "Tostada de aguacate",
          "Shakshuka con pan de masa madre",
          "Pan de plátano con nuez y mantequilla de miel",
        ],
        sortOrder: 1,
      },
      {
        id: "menu_brunch-sin-gluten",
        slug: "brunch-sin-gluten",
        name: "Brunch Sin Gluten",
        description: "Pensado para celiacas y sensibles al gluten.",
        pricingType: "INCLUDED",
        priceCents: 0,
        tags: ["sin gluten", "cuidado"],
        dietaryTags: ["GLUTEN_FREE"],
        itemNames: ["Parfait de yogurt", "Chilaquiles de tortilla de maíz", "Panqué de almendra y naranja"],
        sortOrder: 2,
      },
      {
        id: "menu_sabores-peru-mexico",
        slug: "sabores-peru-mexico",
        name: "Sabores Perú x México",
        description: "Upgrade de autor: ceviche, causa limeña y chilaquiles a la huancaína.",
        pricingType: "PER_GUEST",
        priceCents: mx(250),
        tags: ["fusión", "de autor", "temático"],
        dietaryTags: [],
        itemNames: ["Ceviche clásico de pescado", "Causa limeña de pollo", "Tiradito nikkei de salmón"],
        sortOrder: 3,
      },
      {
        id: "menu_brunch-premium",
        slug: "brunch-premium",
        name: "Brunch Premium",
        description: "Salmón ahumado, rib eye, tabla de quesos y torre de macarons.",
        pricingType: "PER_GUEST",
        priceCents: mx(380),
        tags: ["premium", "celebración"],
        dietaryTags: [],
        itemNames: [
          "Tabla de quesos y charcutería",
          "Bagel de salmón ahumado",
          "Rib eye con huevo estrellado",
        ],
        sortOrder: 4,
      },
    ],
    addOns: [
      {
        id: "addon_mini-karaoke",
        slug: "mini-karaoke",
        name: "Mini karaoke",
        description: "Consola con pantalla, 2 micrófonos inalámbricos y bocina.",
        category: "ENTERTAINMENT",
        pricingType: "FLAT",
        priceCents: mx(2_800),
        maxQuantity: 1,
        sortOrder: 0,
      },
      {
        id: "addon_pastel-personalizado",
        slug: "pastel-personalizado",
        name: "Pastel personalizado",
        description: "Pastel de autor para 10–12 porciones con decoración floral.",
        category: "FOOD",
        pricingType: "FLAT",
        priceCents: mx(1_900),
        maxQuantity: 2,
        sortOrder: 1,
      },
      {
        id: "addon_fotografo-2h",
        slug: "fotografo-2h",
        name: "Fotógrafo 2 h",
        description: "Fotógrafa profesional durante 2 horas; 80+ fotos editadas.",
        category: "PHOTO",
        pricingType: "FLAT",
        priceCents: mx(4_500),
        maxQuantity: 2,
        sortOrder: 2,
      },
      {
        id: "addon_mimosa-bar",
        slug: "mimosa-bar",
        name: "Mimosa bar",
        description: "Barra de mimosas con espumoso, jugos naturales y fruta fresca.",
        category: "DRINKS",
        pricingType: "PER_GUEST",
        priceCents: mx(290),
        maxQuantity: 1,
        sortOrder: 3,
      },
      {
        id: "addon_upgrade-floral",
        slug: "upgrade-floral",
        name: "Upgrade floral",
        description: "Centro de mesa abundante con flores premium de temporada.",
        category: "DECOR",
        pricingType: "FLAT",
        priceCents: mx(2_500),
        maxQuantity: 2,
        sortOrder: 4,
      },
      {
        id: "addon_taller-floral",
        slug: "taller-floral",
        name: "Taller floral",
        description: "Cada invitada arma su propio arreglo guiada por nuestra florista.",
        category: "EXPERIENCE",
        pricingType: "PER_GUEST",
        priceCents: mx(650),
        maxQuantity: 1,
        sortOrder: 5,
      },
      {
        id: "addon_papeleria-personalizada",
        slug: "papeleria-personalizada",
        name: "Papelería personalizada",
        description: "Menú impreso, tarjetas de lugar y letrero de bienvenida.",
        category: "PERSONALIZATION",
        pricingType: "FLAT",
        priceCents: mx(1_200),
        maxQuantity: 1,
        sortOrder: 6,
      },
      {
        id: "addon_regalo-homenajeada",
        slug: "regalo-homenajeada",
        name: "Regalo para la homenajeada",
        description: "Caja de regalo curada con vela artesanal y chocolate de autor.",
        category: "PERSONALIZATION",
        pricingType: "FLAT",
        priceCents: mx(950),
        maxQuantity: 2,
        sortOrder: 7,
      },
      {
        id: "addon_video-recap",
        slug: "video-recap",
        name: "Video recap",
        description: "Video vertical de 60 segundos listo para redes.",
        category: "PHOTO",
        pricingType: "FLAT",
        priceCents: mx(3_200),
        maxQuantity: 1,
        sortOrder: 8,
      },
      {
        id: "addon_memory-capsule-premium",
        slug: "memory-capsule-premium",
        name: "Memory Capsule premium",
        description: "Álbum digital curado con fotos de las invitadas.",
        category: "EXPERIENCE",
        pricingType: "FLAT",
        priceCents: mx(1_500),
        maxQuantity: 1,
        sortOrder: 9,
      },
      {
        id: "addon_arco-globos-organico",
        slug: "arco-globos-organico",
        name: "Arco de globos orgánico",
        description: "Arco de globos en tonos de tu paleta.",
        category: "DECOR",
        pricingType: "FLAT",
        priceCents: mx(2_900),
        maxQuantity: 1,
        sortOrder: 10,
      },
      {
        id: "addon_mesa-postres",
        slug: "mesa-postres",
        name: "Mesa de postres mini",
        description: "Selección de 36 mini postres: tartaletas, macarons y brownies.",
        category: "FOOD",
        pricingType: "FLAT",
        priceCents: mx(2_400),
        maxQuantity: 1,
        sortOrder: 11,
      },
    ],
    experiences: [
      {
        id: "exp_signature-brunch",
        slug: "signature-brunch",
        name: "Signature Brunch",
        tagline: "El brunch que siempre quisiste organizar, sin mover un dedo.",
        description:
          "Nuestra experiencia insignia: una mesa larga vestida con lino, flores de temporada y vajilla de porcelana. Ideal para reencuentros y cumpleaños tranquilos.",
        type: "BRUNCH",
        occasions: ["FRIENDS_BRUNCH", "BIRTHDAY", "GATHERING", "BABY_BRUNCH"],
        basePriceCents: mx(14_900),
        baseGuests: 6,
        minGuests: 6,
        maxGuests: 12,
        extraGuestPriceCents: mx(1_500),
        includes: [
          "Mantelería de lino, vajilla de porcelana y cristalería",
          "Centro de mesa con flores de temporada",
          "Café de especialidad, jugos naturales y aguas frescas",
        ],
        featured: true,
        sortOrder: 0,
        styleIds: ["style_natural", "style_minimal", "style_romantico", "style_elegante"],
        menuIds: [
          "menu_brunch-clasico",
          "menu_brunch-garden",
          "menu_brunch-sin-gluten",
          "menu_brunch-premium",
          "menu_sabores-peru-mexico",
        ],
        addOnIds: ALL_ADDONS_BUT_KARAOKE,
        serviceAreaIds: ["area_polanco", "area_granada", "area_irrigacion"],
      },
      {
        id: "exp_birthday-table",
        slug: "birthday-table",
        name: "Birthday Table",
        tagline: "Una mesa de cumpleaños tan especial como ella.",
        description:
          "Diseñamos la mesa alrededor de la homenajeada: sus colores, sus flores favoritas y un letrero de bienvenida con su nombre.",
        type: "CELEBRATION",
        occasions: ["BIRTHDAY", "FRIENDS_BRUNCH", "GATHERING"],
        basePriceCents: mx(16_900),
        baseGuests: 6,
        minGuests: 6,
        maxGuests: 12,
        extraGuestPriceCents: mx(1_700),
        includes: [
          "Letrero de bienvenida con el nombre de la homenajeada",
          "Flores de temporada y velas",
          "Brindis con espumoso o mocktail para todas",
        ],
        featured: true,
        sortOrder: 1,
        styleIds: ["style_romantico", "style_divertido", "style_colorido", "style_elegante", "style_natural"],
        menuIds: [
          "menu_brunch-clasico",
          "menu_brunch-garden",
          "menu_brunch-sin-gluten",
          "menu_brunch-premium",
          "menu_sabores-peru-mexico",
        ],
        addOnIds: ["addon_mini-karaoke", ...ALL_ADDONS_BUT_KARAOKE],
        serviceAreaIds: ["area_polanco", "area_granada", "area_irrigacion"],
      },
      {
        id: "exp_karaoke-mimosas",
        slug: "karaoke-mimosas",
        name: "Karaoke & Mimosas",
        tagline: "Brunch, burbujas y el micrófono abierto para todas.",
        description:
          "Nuestra experiencia más ruidosa: barra de mimosas y equipo de karaoke profesional. Ideal para despedidas de soltera y cumpleaños con mucha energía.",
        type: "THEMED",
        occasions: ["BACHELORETTE", "BIRTHDAY", "FRIENDS_BRUNCH"],
        basePriceCents: mx(17_900),
        baseGuests: 6,
        minGuests: 6,
        maxGuests: 12,
        extraGuestPriceCents: mx(1_800),
        includes: [
          "Equipo de karaoke profesional con 2 micrófonos inalámbricos",
          "Barra de mimosas con jugos naturales y espumoso",
          "Mesa decorada con flores y detalles divertidos",
        ],
        featured: true,
        sortOrder: 2,
        styleIds: ["style_divertido", "style_colorido", "style_minimal"],
        menuIds: ["menu_brunch-clasico", "menu_brunch-garden", "menu_brunch-premium"],
        addOnIds: [
          "addon_pastel-personalizado",
          "addon_fotografo-2h",
          "addon_upgrade-floral",
          "addon_papeleria-personalizada",
          "addon_regalo-homenajeada",
          "addon_video-recap",
          "addon_memory-capsule-premium",
          "addon_arco-globos-organico",
          "addon_mesa-postres",
        ],
        serviceAreaIds: ["area_polanco", "area_granada", "area_irrigacion"],
      },
      {
        id: "exp_bridal-brunch",
        slug: "bridal-brunch",
        name: "Bridal Brunch",
        tagline: "Para celebrar a la novia rodeada de las que más la quieren.",
        description:
          "Una mesa nupcial con flores blancas, follaje y cristalería fina. Si quieres, sumamos taller floral o fotógrafa.",
        type: "CELEBRATION",
        occasions: ["BRIDAL", "BACHELORETTE", "BABY_BRUNCH"],
        basePriceCents: mx(19_900),
        baseGuests: 6,
        minGuests: 6,
        maxGuests: 12,
        extraGuestPriceCents: mx(1_900),
        includes: [
          "Mesa nupcial con flores blancas y follaje",
          "Cristalería fina y candelabros",
          "Brindis de bienvenida con espumoso",
          "Dinámica de consejos y buenos deseos",
        ],
        featured: false,
        sortOrder: 3,
        styleIds: ["style_elegante", "style_romantico", "style_minimal", "style_natural"],
        menuIds: [
          "menu_brunch-clasico",
          "menu_brunch-garden",
          "menu_brunch-sin-gluten",
          "menu_brunch-premium",
        ],
        addOnIds: ALL_ADDONS_BUT_KARAOKE,
        serviceAreaIds: ["area_polanco", "area_granada", "area_irrigacion"],
      },
      {
        id: "exp_peru-x-mexico",
        slug: "peru-x-mexico",
        name: "Perú x México",
        tagline: "Dos cocinas que se entienden de maravilla, en tu mesa.",
        description:
          "Brunch temático de fusión peruano-mexicana con cocina de autor, textiles artesanales y mucho color.",
        type: "THEMED",
        occasions: ["FRIENDS_BRUNCH", "BIRTHDAY", "GATHERING", "CORPORATE"],
        basePriceCents: mx(18_500),
        baseGuests: 6,
        minGuests: 6,
        maxGuests: 12,
        extraGuestPriceCents: mx(1_800),
        includes: ["Menú de fusión Perú x México", "Mesa con textiles artesanales"],
        featured: false,
        sortOrder: 4,
        styleIds: ["style_colorido", "style_natural", "style_divertido"],
        menuIds: ["menu_brunch-clasico", "menu_brunch-garden", "menu_sabores-peru-mexico"],
        addOnIds: [
          "addon_mini-karaoke",
          "addon_pastel-personalizado",
          "addon_fotografo-2h",
          "addon_upgrade-floral",
          "addon_papeleria-personalizada",
          "addon_video-recap",
          "addon_memory-capsule-premium",
        ],
        serviceAreaIds: ["area_polanco", "area_granada", "area_irrigacion"],
      },
    ],
  };
}

export const ALL_STYLE_SLUGS = STYLES;

export function baseInput(overrides: Partial<DesignerInput> = {}): DesignerInput {
  return {
    occasion: "BIRTHDAY",
    profile: "Mi hermana Sofi cumple 30, ama el café de especialidad y las flores",
    honoreeAge: 30,
    guestCount: 8,
    budgetRangeId: "budget_3",
    tastes: "chilaquiles, pop de los 2000 y flores",
    colors: ["#E9C9BE", "#A3B18A"],
    vibes: ["botanico", "romantico"],
    serviceArea: "area_polanco",
    dietary: [],
    ...overrides,
  };
}
